// This code is generated automatically by JetBrains.IconDataProvider
// Do not edit this file manually

using System.Collections.Generic;
using System.Drawing;
using System.Runtime.CompilerServices;

namespace JetBrains.Icons
{
    public partial class JetBrainsIconDataProvider
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public virtual partial List<JetBrainsIconData> ProvideData(JetBrainsIconKind kind)
        {
            return kind switch
            {
                JetBrainsIconKind.warningDialog => new List<JetBrainsIconData>
                {
                    new JetBrainsIconData(
                        "M12.72 2.74194C13.2889 1.75269 14.7111 1.75269 15.28 2.74194L26.7998 22.7742C27.3687 23.7634 26.6576 25 25.5198 25H2.4802C1.34244 25 0.631339 23.7634 1.20022 22.7742L12.72 2.74194Z",
                        "#FCC75B"
                    ),
                    new JetBrainsIconData(
                        "M15.3 10C15.3 9.28203 14.718 8.7 14 8.7C13.282 8.7 12.7 9.28203 12.7 10L15.3 10ZM12.7 15.5C12.7 16.218 13.282 16.8 14 16.8C14.718 16.8 15.3 16.218 15.3 15.5L12.7 15.5ZM12.7 10L12.7 15.5L15.3 15.5L15.3 10L12.7 10Z",
                        "#7D5020"
                    ),
                    new JetBrainsIconData(
                        "M15.5 20.5C15.5 21.3284 14.8284 22 14 22C13.1716 22 12.5 21.3284 12.5 20.5C12.5 19.6716 13.1716 19 14 19C14.8284 19 15.5 19.6716 15.5 20.5Z",
                        "#7D5020"
                    ),
                },
                JetBrainsIconKind.propertyReadStatic => new List<JetBrainsIconData>
                {
                    new JetBrainsIconData(
                        "M9.5863,13.4999 L13.5003,9.5859 L14.5003,10.5869 C14.8193,9.7859 15.0003,8.9149 15.0003,7.9999 C15.0003,4.1339 11.8653,0.9999 8.0003,0.9999 C4.1343,0.9999 1.0003,4.1339 1.0003,7.9999 C1.0003,9.5639 1.5203,11.0049 2.3873,12.1699 C3.0513,12.4239 3.5763,12.9489 3.8293,13.6119 C4.9953,14.4799 6.4353,14.9999 8.0003,14.9999 C8.9143,14.9999 9.7853,14.8189 10.5863,14.5009 L9.5863,13.4999 Z",
                        "#B99BF8"
, 0.6
                    ),
                    new JetBrainsIconData(
                        "M3.0004,14.4999 C3.0004,15.3279 2.3284,15.9999 1.5004,15.9999 C0.6714,15.9999 0.0004,15.3279 0.0004,14.4999 C0.0004,13.6719 0.6714,12.9999 1.5004,12.9999 C2.3284,12.9999 3.0004,13.6719 3.0004,14.4999",
                        "#62B543"
                    ),
                    new JetBrainsIconData(
                        "13.5 16 11 13.5 13.5 11 16 13.5",
                        "#9AA7B0"
                    ),
                    new JetBrainsIconData(
                        "M0.9974,2.8021 C0.9974,3.83569336 1.23855513,4.8771 2.5354,4.8771 C3.83224487,4.8771 4,3.4641 4,2.7921 C4,2.1061 3.90228271,0.7461 2.5244,0.7461 C1.14651729,0.7461 0.9974,1.76850664 0.9974,2.8021 Z M1,5 C1.008,5.074 1.00713333,6.074 0.9974,8 L0.0004,8 L0.0004,0.0001 L0.9974,0.0001 L0.9974,0.7461 C1.36693099,0.248766667 1.93993099,0.0001 2.7164,0.0001 C3.88110352,0.0001 5.0004,0.578186035 5.0004,2.8021 C5.0004,5.02601396 3.65454102,5.6231 2.7164,5.6231 C2.09097266,5.6231 1.51883932,5.4154 1,5 Z",
                        "#231F20"
, 0.7
, new Point(6, 5)
                    ),
                },
                JetBrainsIconKind.propertyRead => new List<JetBrainsIconData>
                {
                    new JetBrainsIconData(
                        "M8.0005,1 C4.1345,1 1.0005,4.134 1.0005,8 C1.0005,9.564 1.5205,11.005 2.3875,12.17 C3.0515,12.424 3.5765,12.949 3.8295,13.612 C4.9955,14.48 6.4355,15 8.0005,15 C11.8655,15 15.0005,11.866 15.0005,8 C15.0005,4.134 11.8655,1 8.0005,1",
                        "#B99BF8"
, 0.6
                    ),
                    new JetBrainsIconData(
                        "M3.0005,14.5 C3.0005,15.328 2.3285,16 1.5005,16 C0.6715,16 0.0005,15.328 0.0005,14.5 C0.0005,13.672 0.6715,13 1.5005,13 C2.3285,13 3.0005,13.672 3.0005,14.5",
                        "#62B543"
                    ),
                    new JetBrainsIconData(
                        "M0.9974,2.8021 C0.9974,3.83569336 1.23855513,4.8771 2.5354,4.8771 C3.83224487,4.8771 4,3.4641 4,2.7921 C4,2.1061 3.90228271,0.7461 2.5244,0.7461 C1.14651729,0.7461 0.9974,1.76850664 0.9974,2.8021 Z M1,5 C1.008,5.074 1.00713333,6.074 0.9974,8 L0.0004,8 L0.0004,0.0001 L0.9974,0.0001 L0.9974,0.7461 C1.36693099,0.248766667 1.93993099,0.0001 2.7164,0.0001 C3.88110352,0.0001 5.0004,0.578186035 5.0004,2.8021 C5.0004,5.02601396 3.65454102,5.6231 2.7164,5.6231 C2.09097266,5.6231 1.51883932,5.4154 1,5 Z",
                        "#231F20"
, 0.7
, new Point(6, 5)
                    ),
                },
                JetBrainsIconKind.warningDialog_dark => new List<JetBrainsIconData>
                {
                    new JetBrainsIconData(
                        "M12.72 2.74194C13.2889 1.75269 14.7111 1.75269 15.28 2.74194L26.7998 22.7742C27.3687 23.7634 26.6576 25 25.5198 25H2.4802C1.34244 25 0.631339 23.7634 1.20022 22.7742L12.72 2.74194Z",
                        "#F2C55C"
                    ),
                    new JetBrainsIconData(
                        "M15 9C15 8.44772 14.5523 8 14 8C13.4477 8 13 8.44771 13 9L13 15C13 15.5523 13.4477 16 14 16C14.5523 16 15 15.5523 15 15L15 9Z",
                        "#2B2D30"
                    ),
                    new JetBrainsIconData(
                        "M14 22C14.8284 22 15.5 21.3284 15.5 20.5C15.5 19.6716 14.8284 19 14 19C13.1716 19 12.5 19.6716 12.5 20.5C12.5 21.3284 13.1716 22 14 22Z",
                        "#2B2D30"
                    ),
                },
                JetBrainsIconKind.addFile => new List<JetBrainsIconData>
                {
                    new JetBrainsIconData(
                        "M7 1L3 5H7V1Z",
                        "#6E6E6E"
                    ),
                    new JetBrainsIconData(
                        "M10 14V15H3V6H8V1H13V7H10V10H7V14H10Z",
                        "#6E6E6E"
                    ),
                    new JetBrainsIconData(
                        "M13 11H16V13H13V16H11V13H8V11H11V8H13V11Z",
                        "#6E6E6E"
                    ),
                },
                JetBrainsIconKind.addFile_dark => new List<JetBrainsIconData>
                {
                    new JetBrainsIconData(
                        "M7 1L3 5H7V1Z",
                        "#AFB1B3"
                    ),
                    new JetBrainsIconData(
                        "M10 14V15H3V6H8V1H13V7H10V10H7V14H10Z",
                        "#AFB1B3"
                    ),
                    new JetBrainsIconData(
                        "M13 11H16V13H13V16H11V13H8V11H11V8H13V11Z",
                        "#AFB1B3"
                    ),
                },
                _ => new List<JetBrainsIconData>()
            };
        }
    }
}
